import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

/**
 * GET /api/bookings/[id]/complete?token=...
 * Called when tourist scans the QR code generated by the guide.
 * Validates the one-time token and triggers escrow release (COMPLETED status).
 */
export async function GET(
  req: Request,
  { params }: { params: { id: string } }
) {
  const { searchParams } = new URL(req.url);
  const token = searchParams.get("token");

  if (!token) {
    return NextResponse.json({ message: "Missing token" }, { status: 400 });
  }

  try {
    const booking = await prisma.booking.findUnique({
      where: { id: params.id },
      include: {
        gig: {
          include: {
            guide: { select: { id: true, name: true, email: true, walletAddress: true } },
          },
        },
        tourist: { select: { id: true, name: true, email: true } },
      },
    });

    if (!booking) {
      return NextResponse.json({ message: "Booking not found" }, { status: 404 });
    }

    // Validate token
    if (!booking.completionToken || booking.completionToken !== token) {
      return NextResponse.json({ message: "Invalid or already used QR code." }, { status: 400 });
    }

    if (!booking.completionTokenExpiresAt || booking.completionTokenExpiresAt < new Date()) {
      return NextResponse.json({ message: "QR code has expired. Ask the guide to generate a new one." }, { status: 400 });
    }

    const allowedStatuses = ["CONFIRMED", "PAID"];
    if (!allowedStatuses.includes(booking.status)) {
      return NextResponse.json({ message: "Booking is not in a completable state. Status: " + booking.status }, { status: 400 });
    }

    // --- Trigger escrow release (same logic as PATCH status=COMPLETED) ---

    const guideAmount = booking.guide_price ?? (booking.totalPriceUSD - (booking.platform_fee ?? booking.totalPriceUSD * 0.1));
    const commissionAmount = booking.platform_fee ?? (booking.totalPriceUSD - guideAmount);
    const guideWallet = booking.guideWalletSnapshot || booking.gig.guide.walletAddress || "unknown";
    let releaseHash = booking.txHash || null;

    if (process.env.RELAYER_PRIVATE_KEY || process.env.DEPLOYER_PRIVATE_KEY) {
      try {
        const { executeGaslessRelease } = await import("@/lib/crypto/gaslessRelayer");
        const relayerResult = await executeGaslessRelease(booking.id);
        if (relayerResult?.txHash) {
          releaseHash = relayerResult.txHash;
        }
      } catch (onChainErr: any) {
        console.warn("[QR Complete] Gasless on-chain release notice:", onChainErr.message);
      }
    }

    // Invalidate token + mark COMPLETED in a transaction
    await prisma.$transaction([
      prisma.booking.update({
        where: { id: booking.id },
        data: {
          status: "COMPLETED",
          completionToken: null,         // one-time: invalidate immediately
          completionTokenExpiresAt: null,
        },
      }),
      prisma.escrowPayout.upsert({
        where: { bookingId: booking.id },
        update: {
          status: "COMPLETED",
          releaseHash,
        },
        create: {
          bookingId: booking.id,
          guideId: booking.gig.guide.id,
          guideWallet,
          guideAmountUSD: guideAmount,
          commissionAmountUSD: commissionAmount,
          releaseHash,
          status: "COMPLETED",
        },
      }),
      prisma.platformRevenue.create({
        data: {
          source: "BOOKING_COMMISSION",
          amountUSDT: commissionAmount,
          txHash: releaseHash,
          referenceId: booking.id,
        },
      }),
      prisma.paymentAuditLog.create({
        data: {
          bookingId: booking.id,
          txHash: releaseHash,
          source: "QR_HANDSHAKE",
          status: "SUCCESS",
          rawPayload: { token: token.slice(0, 8) + "..." },
        },
      }),
    ]);

    // --- Gamification: XP for guide ---
    try {
      const xpEarned = Math.max(100, Math.round(booking.totalPriceUSD * 10));
      const guide = await prisma.user.findUnique({ where: { id: booking.gig.guide.id } });
      if (guide) {
        const newXp = (guide.xp || 0) + xpEarned;
        const newLevel = Math.floor(newXp / 1000) + 1;
        const oldLevel = guide.level || 1;
        await prisma.user.update({ where: { id: guide.id }, data: { xp: newXp, level: newLevel } });

        await prisma.mail.create({
          data: {
            recipientId: guide.id,
            subject: "Escrow Released via QR Handshake — You Earned " + guideAmount.toFixed(2) + " USDC (+${xpEarned} XP)",
            body: "The tourist scanned your QR code confirming completion of \"" + booking.gig.title + "\". Your net earnings of " + guideAmount.toFixed(2) + " USDC have been released. You earned +" + xpEarned + " XP.",
          },
        });

        if (newLevel > oldLevel) {
          await prisma.mail.create({
            data: {
              recipientId: guide.id,
              subject: "Level Up: Reached Level " + newLevel + "!",
              body: "Congratulations on leveling up to Level " + newLevel + "! Your guide rank has been boosted.",
            },
          });
        }

        // Payout email
        const { triggerGuidePayoutEmail } = await import("@/lib/email");
        await triggerGuidePayoutEmail(booking.id, guide.email, guide.name, booking.gig.title, guideAmount, commissionAmount, xpEarned).catch(console.error);
      }

      // Tourist completion email
      if (booking.tourist?.email) {
        const { triggerTouristCompletionEmail } = await import("@/lib/email");
        await triggerTouristCompletionEmail(booking.id, booking.tourist.email, booking.gig.title, booking.gig.guide.name || "your guide", booking.totalPriceUSD).catch(console.error);
      }
    } catch (postErr) {
      console.error("[QR Complete] Post-completion side effects failed:", postErr);
    }

    // Redirect tourist to their dashboard with success flag
    const appUrl = process.env.NEXTAUTH_URL || "https://guidebloc.com";
    return NextResponse.redirect(appUrl + "/dashboard/tourist/bookings?completed=" + booking.id);
  } catch (error: any) {
    console.error("[QR Complete Error]", error);
    return NextResponse.json({ message: error.message || "Internal server error" }, { status: 500 });
  }
}
